### ISSUE TITLE
Data fit for growth curves

### ISSUE THREAD

**Issue by Slesarew** [Alzymologist/yeast#16]
There are 2 approaches here.

1. Exponential growth.
2. Both exponential growth and stationary phase

# Exponential growth

Some rudimentary code that does fitting is already present in processing code. We should implement data discard algorithm to discard obviously off points here; this is difficult task to automate, yet we should not be doing it manually really. Expected doubling times could be 0.5-4h although could also extend to 10h and further in very unfavorable conditions.

# Exponential + stationary

Here we would not be able to linearize things. We should fit the data using some version of Kalman filter.

Growth rate is governed by Monod/Michaels-Menten equation,

`dY/dt = Y*K*(S/(Ks - S))`

where `Y` is yeast concentration, `S` is sugar concentration, `t` is time, and `K`, `Ks` are fit parameters. Sugar concentration has a dependancy (linear in first approximation) with optically measured density obtained in there experiments; thus we have indication of value and parameter influencing its rate of change. Rate of sugar consumption is directly proportional to yeast growth rate, thus

`dS/dt = Y*K1*(S/(Ks-S))`

where K1 is another parameter (`K1 = K*Km` where `Km` is amount of sugar that should be consumed for cell to grow to splitting size)

We should fit these equations and infer from probability of yeast growth parameters being this different probability of culture being indeed monoclonal.

Most important application of this feature would be uniformity tests, but other tests, like fermentation rate and lag time estimations would benefit from this as well.

**Comment by Zhenya-Barannik** [comment]
The data is fitted using logistic model in the parameter space of the required dimensionality.
