### ISSUE TITLE
Stock solutions should be orphans

### ISSUE THREAD

**Issue by Slesarew** [Alzymologist/yeast#33]
There is no need to look for parent/participant records in stock data, they are always made fresh

**Comment by Zhenya-Barannik** [comment]
Stock solutions can now be orphans (see feature-2 branch). Also orphan graph components are now properly drawn:
![genealogy](https://github.com/Alzymologist/yeast/assets/69721131/a1ee9d6c-3ccf-403b-ab42-48d5b7564f37)
