### ISSUE TITLE
Should isolate, isolation, isolate-edta be different?

### ISSUE THREAD

**Issue by Zhenya-Barannik** [Alzymologist/yeast#37]
Should 
```
protocol.name = "isolate"
protocol.name = "isolation"
protocol.name = "isolate-edta"
```
be different?

**Comment by Slesarew** [comment]
`isolate-edta` is different protocol, but it did not work so far. Maybe we should just remove it, I don't know. In essence, it's also isolation, so for now we can render them as same.

`isolate` and `isolation` are identical

**Comment by Zhenya-Barannik** [comment]
I have renamed all instances of "isolate" to "isolation".
